[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/"
  to = "https://www.linkedin.com/in/kylegwang"
  status = 200
  force = true
