[[build]]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "https://www.linkedin.com/in/kylegwang/"
  status = 200
  force = true

[[plugins]]
  package = "netlify-plugin-cypress"
